import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {
  Container,
  Button,
  Input,
  Spacer,
  Text,
  Link
} from '@nextui-org/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextUI ~ Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        as="main"
        display="flex"
        direction="column"
        justify="center"
        alignItems="center"
        style={{ height: '100vh' }}
      >
        <Spacer />
      <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={200} />
      <Spacer />
      <Text h1>
        Welcome to &nbsp;
        <Link
          color
          href="https://sugitlab.work"
          target="noopener noreferer"
        >
          Sugitlab
        </Link>
      </Text>
        <Spacer />
        <Input clearable labelPlaceholder="Type something" />
        <Spacer />
        <Button color="lightBlue" >
          <a
            href="https://github.com/sugitlab"
            target="_blank"
            rel="noopener noreferer noreferrer"
          >
            Show on GitHub
          </a>
        </Button>
    </Container>

    </div>
  )
}

export default Home
